# code below is taken from https://github.com/fchollet/keras/blob/master/.travis.yml
sudo: required
dist: trusty
language: python
python: # Only two versions for now
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib
  # install TensorFlow from https://storage.googleapis.com/tensorflow/
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp34-cp34m-linux_x86_64.whl;
    fi
script:
  - sed -i -- 's/range(100)/range(1)/g' ??_*.py # change range to 1 for quick testing
  - python 03_net.py # run this first to download MNIST file
  # run all python files in parallel, http://stackoverflow.com/questions/5015316
  - ls ??_*.py|xargs -n 1 -P 3 python
